### ISSUE TITLE
Add pypi secrets in GitHub

### ISSUE THREAD

**Issue by g4challenge** [emergotechnologies/helium-api-wrapper#8]
Please insert the necessary secrets in GitHub so we can build and publish the package to pypi and test.pypi.
The neccesary secrets are
${{ secrets.TEST_PYPI_TOKEN }}
${{ secrets.PYPI_TOKEN }}
${{ secrets.GITHUB_TOKEN }}
I don't know if this github_token is neccesary, or if it's auto available it's at the end of the build script which was available in GitLab.
Please put the secrets in both repositories

**Comment by simonpfeifhofer** [comment]
@g4challenge @elauser added TEST_PYPI_TOKEN and PYPI_TOKEN in both repositories.  GITHUB_TOKEN should be available out of the box.
Please test and provide feedback.
